version: '3'
services:
  app:
    build: ./
    tty: true
    env_file:
      - ./.env
    environment:
      - DISPLAY=${PYGAME_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/home/docker/app
